In [1]:
import numpy as np
tab=np.array([1,2,3])
list = tab.tolist()
print (list )

[1, 2, 3]


In [5]:
import numpy as np
tableau=np.arange(6).reshape(2,3)
diag = np.trace(tableau)
print(tableau)
print (diag)


[[0 1 2]
 [3 4 5]]
4


In [13]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))





Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [11]:
import numpy as np
A=np.arange(8).reshape(2,4)
B=np.arange(8).reshape(2,4)
C=A+B
print(A)
print(B)
print(C)

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 0  2  4  6]
 [ 8 10 12 14]]


In [12]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.65764441 0.00867368 0.51320378 0.95593513 0.40013968 0.82413591
  0.97498788 0.96690685 0.0875258  0.24774874]
 [0.28272074 0.96179173 0.60138853 0.09577231 0.39083528 0.83831853
  0.33994467 0.76485468 0.88871198 0.65626999]
 [0.47450098 0.70605538 0.22360058 0.34687679 0.39928598 0.60150218
  0.04667416 0.30176499 0.64989982 0.150735  ]
 [0.85633211 0.37480678 0.82627498 0.71785257 0.41759059 0.56101359
  0.38851995 0.21589845 0.729889   0.93225155]
 [0.86132025 0.32660938 0.52398303 0.27886286 0.97331359 0.90722138
  0.41580799 0.53513613 0.9242028  0.96386625]]

Subtract the mean of each row of the said matrix:

[[ 0.09395422 -0.5550165  -0.05048641  0.39224494 -0.1635505   0.26044573
   0.41129769  0.40321666 -0.47616439 -0.31594145]
 [-0.2993401   0.37973088  0.01932768 -0.48628853 -0.19122556  0.25625769
  -0.24211618  0.18279384  0.30665113  0.07420915]
 [ 0.08441139  0.31596579 -0.16648901 -0.04321279  0.00919639  0.21141259
  -0.34341542 -0.0883246   0.2